name: repit_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^5.0.1
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.2
  google_fonts: ^4.0.3
  image_picker: ^1.0.4
  package_info: ^2.0.2
  photo_view: ^0.14.0
  shared_preferences: ^2.0.18
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
