// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd-pawT7NqbNDPaiShKGEa13UPH2D1Cyk',
    appId: '1:347010207315:web:ecb184ec943bd553a780a6',
    messagingSenderId: '347010207315',
    projectId: 'repit-1580d',
    authDomain: 'repit-1580d.firebaseapp.com',
    storageBucket: 'repit-1580d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-EGr3BV4lfHHPASS_epFEZ2mKNbaNC0',
    appId: '1:347010207315:android:f0c58cb6216d2d20a780a6',
    messagingSenderId: '347010207315',
    projectId: 'repit-1580d',
    storageBucket: 'repit-1580d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByxtowiZNcBj9JE7iRSExzqqReIIFZxPA',
    appId: '1:347010207315:ios:b9d21d15597dbacca780a6',
    messagingSenderId: '347010207315',
    projectId: 'repit-1580d',
    storageBucket: 'repit-1580d.appspot.com',
    iosBundleId: 'com.example.repitApp',
  );
}
